Unify version used of Google.Apis package. (#660)
Fix the error:
System.IO.FileLoadException: Could not load file or assembly 'Google.Apis, Version=1.27.1.0, Culture=neutral
when using Google.Cloud.Storage.V1 2.0.0.

(cherry picked from commit 288510978f26779196578bd2882703adf1e1dbfa)