Restore GxHttpContextAccesor lost at #393 Http dispatcher refactoring (#596)
* Restore GxHttpContextAccesor lost at #393 Http dispatcher refactoring
Fixes the error:
System.ObjectDisposedException: IFeatureCollection has been disposed.
Object name: 'Collection'.
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
 According to:
https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AspNetCoreGuidance.md#do-not-store-ihttpcontextaccessorhttpcontext-in-a-field

* Remove unneeded Console.Writeline.

* Reduce max number of concurrent threads on test. Concurrency is tested anyway and test output gets smaller.

* Complete code for testing the error:
System.ObjectDisposedException: IFeatureCollection has been disposed.
Object name: 'Collection'.
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ContextDisposed()

* Fix build error on GXMultiCall.webExecute method.

* Add output message for unit test on dfrgtxt to diagnose failing tests.

* Specify full path for tests with FileIO to avoid conflict with aspnetcore tests since GxContext.StaticPhysicalPath() returns a different value depending on the context (web or batch).

* Set BaseDir for FullTextSearchTests.

* Override Write method for GxHttpAzureResponse because WriteAsync is not supported.

* Restore synchronous writing on httpreponse because GxHttpAzureResponse does not support it.
For writing json should be used WriteAsJsonAsync which is supported by GxHttpAzureResponse. Soon it will be analyzed.