Fixes for .netcore and iseries connection. (#459)
* Fixes for .netcore and iseries connection.

* Method Db2DataReader.GetString and Db2DataReader.GetValue cannot be executed twice on the same instance.
The second time throws the error:
System.InvalidOperationException: There is no more data to return.
   at IBM.Data.Db2.DB2DataReader.GetString(Int32 i)
   at GeneXus.Data.GxDataReader.GetString(Int32 i)

So that as a workaround, it is read from the last GetValues used to store data in cache, because the value is read twice only when caching is enabled.